[versions]
jacksonKotlin = "2.16.1"
junit-jupiter = "5.10.1"
hamkrest = "1.8.0.1"
kotlin = "1.9.22"
kotlinReflect = "1.9.22"
lombok = "1.18.30"
springboot = "3.2.3"
springDependencyManagementVersion = "1.1.4"

[libraries]
springBootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springboot" }
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springboot" }

jacksonKotlinModule = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonKotlin" }
kotlinReflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = {id ="org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin"}
springBoot = { id = "org.springframework.boot", version.ref = "springboot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }
